### ISSUE TITLE
Error when importing Carpert.js from npm

### ISSUE THREAD

**Issue by DarekPobozniak** [mateuszgachowski/Carpet.js#11]
Hi Mateusz,
Installing `carpet.js` from npm (not using bower) and including it using ES2015 `import` statement:

```
import Carpet from 'carpet.js';

Carpet.registerComponent('componentName', function () {
  // ...
});
```

produces error:

```
ERROR in ./~/carpet.js/Gruntfile.js
Module not found: Error: Cannot resolve module 'load-grunt-tasks' in /node_modules/carpet.js
 @ ./~/carpet.js/Gruntfile.js 110:2-29
```

It seems that `load-grunt-tasks` is not installed during installing library from npm.

In `package.json`
changing `"main": "Gruntfile.js"` 
to `"main": "dist/carpet.js"` 
seemed to solve the issue.

Thanks,
Darek.

**Comment by mateuszgachowski** [comment]
Hi Darek :)

Yes, this seems a problem with mainfile - imports in ES6 may look for main file while you import whole library. Ill do a PR soon, but meanwhile you can import it as alias `carpet.js/dist/carpet.min.js` or something.

**Comment by DarekPobozniak** [comment]
Importing `carpet.js/dist/carpet.min.js` produces the same error.

Anyway, I'm waiting for your PR :)

Thanks,
Darek.

**Comment by mateuszgachowski** [comment]
Darek,

Which version of Carpet do you use?

Cheers,
Mateusz

**Comment by DarekPobozniak** [comment]
Carpet v3.1.1

**Comment by mateuszgachowski** [comment]
This should be working now. Please switch to `3.1.2` version and it should be cool :)

Cheers,
Mateusz

**Comment by tvardy** [comment]
Until now in all my projects I've been using a small JSPM's override setting:

```
"overrides": {
  "github:mateuszgachowski/Carpet.js@3.1.1": {
    "main": "dist/casper"
  }
}
```

And never even thought of... just letting you know 🤣 

Good job @DarekPobozniak 👍

**Comment by mateuszgachowski** [comment]
Hehe :) We all need to learn from @DarekPobozniak that life is simpler if you only ask :)

**Comment by DarekPobozniak** [comment]
Good job guys! 👍
