### ISSUE TITLE
Prepare some examples of use

### ISSUE THREAD

**Issue by mateuszgachowski** [mateuszgachowski/Carpet.js#4]
Examples of use of Carpet.js:
- ~~Minimal application~~ ✓
- Form Module (with validation)
- ~~Passing settings to the module~~ ✓
- ~~Registering custom components~~ ✓
- Carpet.js + jQuery: how to use the jQuery context
- Carpet.js + Bootstrap: samples
- Modules with no 'auto init' - how to make use of PubSub or event-triggering
- Connecting modules and their behaviour with each other
- Using advice to extend framework functionality

For now examples can be stored in the repo, in the future we can create a separate repo for them

**Comment by yckart** [comment]
Hmm, I think the "minimal application"-example is not *done* yet. It would great, to see a bit more of carpets magic in it. At least we should replace page contents dynamically and maybe minimal url/dom-routing, based on the navigation-module...

**Comment by mateuszgachowski** [comment]
Hi @yckart,
Thank you for your comment.

I think that the minimal application should represent the most basic usage of Carpet. What you are talking about is more like a robust and full working application - which I have to agree - should be added as an example too. Carpet is build with simplicity in mind and its most important feature is weight.
I will have to prepare lot of external component to resolve problems like data-binding, routing etc.
Anyway, I would like to have something like this on the roadmap of this project, so I will appreciate any help to achieve that :)
