### ISSUE TITLE
Multiple modules per element

### ISSUE THREAD

**Issue by sobstel** [mateuszgachowski/Carpet.js#6]
Why don't you allow multiple modules per element: `data-module="module1 module2"`. Implementation should be easy and sometimes it's better to categorize modules by some common shared logic, not by element itself (eg. modules having tab navigation, modules having "load more" pagination, etc).

Pseudo-code:
```
 moduleNames = domModule.getAttribute('data-module').split(" ");
 for each (moduleNames....
```

**Comment by romannowicki** [comment]
@sobstel allowing to have multiple modules in `data-module` attribute will add problem with separation of  module settings as currently they are collected in one `data-settings` attribute

**Comment by mateuszgachowski** [comment]
Its the same behaviour as Bootstrap have for data-trigger, for example:
`data-trigger="modal"`

If you need to trigger two modules one-by-one on the same element it is just impossible.

Although you can try hack like this (not recommened):
http://stackoverflow.com/questions/16402390/bootstrap-control-with-multiple-data-toggle

The other way to do it is to have a "master" module and "submodules" [without init method].
The master module can trigger submodules manually in its init method (also not recommented).

**Comment by maciejsmolinski** [comment]
I agree with @sobstel here. We try to apply single-responsibility to DOM elements instead of javascript modules. It's more or less like "This element will only do this and nothing else".

If we need to extend the behaviour, the javascript modules grow to 100 lines and more. If we want to share behaviour between some modules, we need to hack things sometimes, because one of the elements that should share the behaviour has other module bound to it already so we initialise module's body on an empty javascript object and sort of "hijack" methods.

In the proposed solution a big advantage will be that modules are going to be really small parts of code instead of big hundred-liners. This helps us keep code really maintainable.

Regarding the shared data-attributes, we can find a workaround such as namespacing data attributes so for example `gallery` module will have `data-gallery-settings` attribute. That's not something really problematic. If we want to provide backwards compatibility, we can simply fallback to `data-settings` if `data-gallery-settings` attribute is not available.

What do you guys think?

**Comment by sobstel** [comment]
It's all about flexibility. Give me a hammer, but don't tell me how to hit. If you don't need multiple modules (because of settings concerns) you can still use it as before. 

One module per block means each block can have one behaviour. World is not that simple. Dog can run, swim and bark, cat can run and meow, duck can swim and quack. Let me have modules by behaviour, not by subject, so run, swim, bark, meow, quack, and not dog, cat, duck (ok, I know my mind is duck-typing infected, but it makes a lot of much sense).

Re: data-settings. It depends on what they're meant for. As I understand they usually contain block-specific stuff (eg. player id for player block), so this actually might be good they're shared.

**Comment by mateuszgachowski** [comment]
Is this what you thought about? If settings are shared between mutliple modules its pretty easy.
https://github.com/mateuszgachowski/Carpet.js/commit/4f312ddfcec8f48378722e1cf4745fc72396f32b

**Comment by romannowicki** [comment]
In that case module name doesn't match anymore. You are trying to change
the concept here, modules have pretty simple construction right now and are
responsible only for one thing initialisation of themselves, and now you
are trying to share they logic/behaviour - it's not module anymore.

**Comment by romannowicki** [comment]
I think that it would be better to have extra data attribute for injecting
behaviours with shared logic that can be used inside module

**Comment by mateuszgachowski** [comment]
This does not change much of the behaviour - you can just attach to the same context multiple modules - but still you can stay with only one. I think its better to give freedom in this matter. For example if you have a "Fixture" row and there are multiple things going on there you can use multiple modules:

HTML:
```
<div class="fixture" data-module="update-score update-bookings" data-settings="{'fixtureId': 1}">
  <span>FCB 0:1 PSG<span>
  <ul>
    <li>Red - L. Messi</li>
  </ul>
</div>
<div class="fixture" data-module="update-score update-bookings" data-settings="{'fixtureId': 1}">
  <span>LIL 0:1 PSG</span>
</div>
```


JS:
```
Carpet.module('update-score', function (exports, settings, context) {

  var refreshScore = function () {
    $.ajax('scoreUrl/' + settings.fixtureId, {...})
  };
  exports.init = function () {
    setInterval(refreshScore, 2000);
  };
});

Carpet.module('update-score', function (exports, settings, context) {

  var refreshBookings = function () {
    $.ajax('bookingsUrl/' + settings.fixtureId, {...})
  };
  exports.init = function () {
    setInterval(refreshBookings, 5000);
  };
});
```

Just to give a sample.

If you create separated modules for `span` and `ul` they will not have shared settings and you will have to take it from the parent (going out of module scope).

**Comment by sobstel** [comment]
+100 for @mateuszgachowski . great example.

Re: module. I thought "module" word refers rather to Module Pattern, which is about encapsulation to avoid naming collision and to avoid global namespace pollution. (https://carldanley.com/js-module-pattern/)

**Comment by romannowicki** [comment]
make sense

**Comment by mateuszgachowski** [comment]
#3.1.0 released

**Comment by mgierok** [comment]
Why not to attach behavior to the parent node?

**Comment by mateuszgachowski** [comment]
In most cases you should do that way. But this flexibility does not break anything - so why not to have it? :)

**Comment by sobstel** [comment]
Because your app will end up suffering "divitis" ;-)

**Comment by mateuszgachowski** [comment]
@sobstel +1 :D

**Comment by tvardy** [comment]
I was thinking on changing a bit the ```data-``` attributes' structure, by moving the ```data-settings object``` into ```data-module```.

E. g. If you'd like to run multiple modules that need different configs you could use:

    data-module="{
      moduleOne: {
        foo: 'bar'
      },
      moduleTwo: {
        bar: 'baz'
      }
    }"

And there will be no need to use ```data-settings``` separately. Or we could use it as an additional configuration common for all the modules.

**Comment by mateuszgachowski** [comment]
Thanks for your comment.
90% of modules have no settings passed into Carpet from my experience. I think this kind of solution will only make it look uglier and not give any pros.
I have added sample PR with multiple modules with shared settings to ease the logic separation of code. I think this is enough for now - what do you think?
